forbiddenflags:
- receive-chat
- allowed-cmds
- blocked-cmds
- send-chat
- invincible
- command-on-entry
- command-on-exit
- console-command-on-entry
- console-command-on-exit
- godmode
- worldedit
- chunk-unload
- passthrough
- price